Petr
ksgl/chat pull request #5
Opened 2018-05-08 06:37 UTC by JIeTPoBu4

Здравстуйте. Посмотрите, пожалуйста.

2018-05-13 09:16 UTC, leshiy1295 requested changes

2018-05-13 09:16 UTC, leshiy1295 commented on src/main.cpp
> +TaskManager &task_manager_obj = TaskManager::instance();
Сейчас нигде не используется...

2018-05-13 09:16 UTC, leshiy1295 commented on src/TaskManager.hpp
> +using json = nlohmann::json;
Сейчас обобщённый TaskManager жёстко привязан к модулю json - нужно их разъединить
Он должен зависеть от абстрактного класса Task, для которого нужно предоставить методы парсинга и разбора в json
саму эту логику нужно будет вынести в отдельный модуль парсера
в объекте же Task хранить Parser * объект, который является наследником от Parser (например, TaskManagerParser), который будет адаптером, то есть ему Вы будете отдавать это поле, ему Вы будете проксировать метод from_json и to_json, а он уже будет реализовывать нужный nlohmann метод to_json и from_json
В итоге всё, что у Вас будет зависеть от JSON - это TaskManagerParser, но TaskManager, Parser и Task - самостоятельные независимые интерфейсы.
Более того, для Task стоит выделить ещё отдельный интерфейс Serializable/JSONSerializable, в котором и будут to_json/from_json, так как это не неотъемлемая часть интерфейса Task, как мне кажется

2018-05-13 09:16 UTC, leshiy1295 commented on src/TaskManager.hpp
> +class task_executor {
а что в итоге с Executor?
Если не нужен - надо убрать комментарий
Но сейчас нет логики обработки элементов очереди...

2018-05-13 09:16 UTC, leshiy1295 commented on src/TaskManager.hpp
> +	task_queue_mutex.lock();
лучше использовать RAII обёртки

2018-05-17 16:32 UTC, Armelior commented on src/TaskManager.hpp
> +#include "json.hpp"
```cpp
#include "json.hpp"
...
using json = nlohmann::json;
```

Вы используете: `nlohmann::json`, `QJsonObject`... И приплели еще чужую либу в виде некоего `json.hpp`.

Проблемы с совместимостью между UI, сетью и TaskManager, нет?

2018-05-31 14:09 UTC, closed without merging